# Changes here will be overwritten by Copier
#
# Updating `_src` could be helpful, see notes at:
# https://github.com/level12/coppy/wiki#creating-a-project
#
# Otherwise, NEVER EDIT MANUALLY
_commit: v1.20251025.1
_src_path: gh:level12/coppy
author_email: randy@syrings.us
author_name: Randy Syring
gh_org: level12
gh_repo: lexe
hatch_version_tag_sign: true
project_name: lexe
py_module: lexe
python_version: '3.14'
script_name: lexe
use_circleci: false
use_gh_nox: true
