stack:
  ident: juke-flask

remotes:
  ghcr:
    url: https://ghcr.io
    username: rsyring
    secret_cmd: op --account my read "op://Private/github-token-packages-ro/token" -n

services:
  redis:
    image: docker:redis:7.4-alpine

  web:
    image: ghcr:level12/juke-inc/juke-flask:latest
    port: 8000
